### PR TITLE
Added tracking for unsuccessful raid mode threads

### PR DESCRIPTION
**Pull request by heftymouse**
Second attempt:
this is such a hack lmfaooo

### CODE REVIEW

**Review by Erisa — CHANGES_REQUESTED** [review]
Rather than just the number of threads, i was more interested in the user submitting and/or the content of the messages, to gauge whether or not those queries were manifested another way (like annoying moderator pings)

**Comment by heftymouse** [comment]
Fair enough, it's pretty useless in its current state
I was thinking of having it log to the investigations channel, similar to how it currently logs bot mentions (with more info of course), do you think that's enough or is there something you'd like to see added?

**Comment by Erisa** [comment]
Investigations channel is already polluted with other stuff, I think using #modmail-logs is probably a better fit but you might want to ask for opinion from other mods before pursuing that. I personally think it's fine there because logs are mostly searched by `!logs` and the increase won't make much impact on browsing thread history.

**Comment by heftymouse** [comment]
Closing this for now since it's useless and there doesn't seem to be much demand for it anyways

**Pull request closed without merging**
